# Setup
title:               IFT6758 Blog
tagline:             ''
description:         ''
url:                 ''
# baseurl:             '/Hockey-prediction'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hung Le
  email:             duyhung2201@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
