# Setup
title:               IFT6758 Blog
tagline:             ''
description:         ''
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gauransh Kumar(Team B03)
  url:               https://gauransh.dev
  email:             gauransh.kumar@umontreal.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
