# Setup
title:               Hockey Prediction Blog
tagline:             'Real-Time NHL Forecasting'
# description:         'Live at: hockey-prediction.streamlit.app | Demo at: https://youtu.be/Lqi4OQlnkHQ'
# url:                 https://hockey-prediction.streamlit.app/'
# baseurl:             '/Hockey-prediction'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hung Le
  email:             duyhung2201@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
