# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    ports:
      - 8000:8000
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
      - COMET_ML_PROJECT_NAME=${COMET_ML_PROJECT_NAME}
      - COMET_ML_WORKSPACE=${COMET_ML_WORKSPACE}


###### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    ports:
      - 8080:8080
    environment:
      - CLIENT_HOST=serving
      - CLIENT_PORT=8000
      