# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:latest
    ports:
      - 8000:8000
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
      - COMET_ML_PROJECT_NAME=${COMET_ML_PROJECT_NAME}
      - COMET_ML_WORKSPACE=${COMET_ML_WORKSPACE}

  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:latest
    environment:
      - SERVING_HOST=serving
      - SERVING_PORT=8000
    ports:
      - 8005:8005
