name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Set to your default branch
  pull_request:
    branches:
      - main  # Set to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7  # Set to your Ruby version

    - name: Build and test
      run: |
        gem install jekyll bundler
        bundle install

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Set to your Jekyll build output directory