name: Jekyll CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.5

    - name: Install dependencies
      run: |
        gem install jekyll bundler
        bundle install

    - name: Build and Test
      run: bundle exec jekyll build

    # Optionally, add a step for any custom scripts or tests you want to run
    # - name: Run custom tests
    #   run: <your_test_script_here>
